backend:
  name: git-gateway
  repo: catuy/catuy.github.io  # Reemplaza con tu usuario y repositorio de GitHub
  branch: master  # O la rama que uses (main, master, etc.)
  auth_scope: repo  # Permisos necesarios
  site_domain: https://catuy.github.io  # Para desarrollo local
  base_url: https://api.netlify.com  # Para desarrollo local
  client_id: Ov23liZ0qzrw82lHZNR7  # Tu Client ID
  client_secret: 4776b6d5347f5b2091198fbc7ba3db0f729073b5  # Tu Client Secret

media_folder: "assets/blogimages"  # Carpeta donde se guardarán las imágenes subidas
public_folder: "/assets/blogimages"  # Ruta pública para acceder a las imágenes
extension: markdown  # Especifica la extensión de los archivos
format: frontmatter  # Formato de los archivos (frontmatter es el predeterminado para Jekyll)

collections:
  - name: "Works"  # Nombre de la colección
    label: "Works"
    folder: "_posts"  # Carpeta donde se guardan los archivos
    create: true  # Permite crear nuevos archivos
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Formato del nombre del archivo
    extension: md  # Especifica la extensión de los archivos
    format: frontmatter  # Formato de los archivos (frontmatter es el predeterminado para Jekyll)
    # summary: "{{title}} - {{description}}"  # Resumen de la entrada
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Visible", name: "visible", widget: "boolean", default: true }  # Campo para mostrar/ocultar
      - { label: "Imágenes", name: "images", widget: "list", field: { label: "Imagen", name: "image", widget: "image" } }  # Lista de imágenes
      - { label: "Etiquetas", name: "tags", widget: "list", default: ["Web"] }  # Campo de etiquetas
      - { label: "Categorías", name: "categories", widget: "list", default: ["todos"] }  # Campo de categorías
      - { label: "Descripción", name: "description", widget: "text" }  # Campo de descripción


  - name: "Pages"  # Nombre de la colección (por ejemplo, para entradas de blog)
    label: "Pages"
    folder: "/"  # Carpeta donde se guardan los archivos
    create: false  # Permite crear nuevos archivos
    slug: ""  # Formato del nombre del archivo
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }