backend:
  name: github
  repo: catuy/catuy.github.io
  branch: master
  base_url: https://catuy-github-io.pages.dev/
  auth_endpoint: /api/auth
  # This line should *not* be indented
publish_mode: editorial_workflow
media_folder: "assets/blogimages"  # Carpeta donde se guardarán las imágenes subidas
public_folder: "/assets/blogimages"  # Ruta pública para acceder a las imágenes
extension: markdown  # Especifica la extensión de los archivos
format: frontmatter  # Formato de los archivos (frontmatter es el predeterminado para Jekyll)
collections:
  - name: "Works"  # Nombre de la colección
    label: "Works"
    folder: "_posts"  # Carpeta donde se guardan los archivos
    create: true  # Permite crear nuevos archivos
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Formato del nombre del archivo
    extension: md  # Especifica la extensión de los archivos
    format: frontmatter  # Formato de los archivos (frontmatter es el predeterminado para Jekyll)
    editor:
      preview: false
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imágenes", name: "images", widget: "list", field: { label: "Imagen", name: "image", widget: "image" } }  # Lista de imágenes
      - { label: "Etiquetas", name: "tags", widget: "list", default: ["Web"] }  # Campo de etiquetas
      - { label: "Categorías", name: "categories", widget: "list", default: ["todos"] }  # Campo de categorías
      - { label: "Descripción", name: "description", widget: "text" }  # Campo de descripción
      - { label: "Content", name: "body", widget: "markdown" }  # Cambia "content" a "body" y usa "markdown"



  - name: "Pages"  # Nombre de la colección (por ejemplo, para entradas de blog)
    label: "Pages"
    folder: "/"  # Carpeta donde se guardan los archivos
    create: false  # Permite crear nuevos archivos
    slug: ""  # Formato del nombre del archivo
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }